### ISSUE TITLE
Alguns problemas :(

### ISSUE THREAD

**Issue by danvitoriano** [alsvinicius/chatbot-trabalho-final#1]
Rapazes, eu tive alguns problemas para rodar o projeto no Intellij, precisei indicar configurações como a versão do JDK e o classpath. 
O bot para /aula, /dolar e /alaska não funcionou para mim. A resposta era: `Não tenho uma resposta para isso`.
Se quiserem testar e ver se isso acontece para vocês, e subirem uma versão corrigida, consigo esperar alguns dias antes de lançar a nota da avaliação, beleza?
Me avisem por aqui se forem fazer isso, senão vou considerar o trabalho como entregue porém com estes pequenos problemas.
Aproveitem e insiram no README estas instruções sobre como instalar o projeto, rodá-lo e como gerar o token e iniciar a interação com o bot do Telegram. As pessoas que acessam seu projeto aqui não sabem como fazer isso!
🚀

**Comment by alsvinicius** [comment]
Professor, bom dia! 

Obrigado pelas indicações. Já vou atuar nesse problema para tentar replicá-lo. Assim que estiver com uma versão atualizada, comento por aqui e fecho a issue. 

Abraços!

**Comment by alsvinicius** [comment]
Olá, professor!

Seguem considerações sobre os problemas levantados:

- erros de instalação: fiz o download do projeto do zero e não tive problemas para executar. Porém, acredito que a provável causa principal para o cenário descrito foi que as configurações do projeto no meu Intellij estavam versionadas no git, e isso pode ter gerado algum conflito. O projeto, apesar de executar normalmente em Java 8, foi criado como a versão 11 como alvo. Talvez isso tenha relação também. De qualquer forma, fiz a exclusão dos arquivos do Intellij do repositório.

- /alaska: houve uma mudança no html do site que quebrou o crawler. Fiz uma correção e acredito que o seletor usado dessa vez é mais "à prova de mudanças".

- /dolar: o serviço usado para receber a cotação do dólar está fora do ar. Para corrigir, comecei a usar outro serviço, que está mais estável e não causará problemas.

- /fiap: acredito que pode estar havendo problemas por não ser um login de aluno acessando a área logada. Estou enviando para seu email da Fiap um login e senha para testes.

- readme.md: fiz alterações para que fique um pouco mais claro o processo de criação do bot através do BotFather e a execução inicial do projeto.

**Comment by danvitoriano** [comment]
agora funcionou muito bem! pena que o dólar está tão alto mesmo 😭 
o README também ficou ótimo!
quando for assim, deixe que a pessoa que abriu a Issue a feche! Eu precisava testar antes para confirmar se a issue estava mesmo fechada! 😞 

de resto, parabéns e obrigado pela agilidade na correção! 🚀
